from __future__ import annotations

import os
import re
import json
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from uuid import uuid4

from preparation.para_type import ParagraphManager, ParsedParaType, ParaInfo


@dataclass
class LatexExportResult:
    """LaTeX 导出结果"""
    export_id: str
    latex_path: str
    success: bool
    error_message: Optional[str] = None
    paragraph_count: int = 0


class LatexExporter:
    """LaTeX 导出器，将文档转换为 LaTeX 格式"""

    # 段落类型到 LaTeX 结构的映射
    PARA_TYPE_TO_LATEX = {
        ParsedParaType.TITLE_ZH: 'title',
        ParsedParaType.TITLE_EN: 'title',
        ParsedParaType.ABSTRACT_ZH: 'abstract',
        ParsedParaType.ABSTRACT_CONTENT_ZH: 'abstract_content',
        ParsedParaType.ABSTRACT_EN: 'abstract',
        ParsedParaType.ABSTRACT_CONTENT_EN: 'abstract_content',
        ParsedParaType.KEYWORDS_ZH: 'keywords',
        ParsedParaType.KEYWORDS_CONTENT_ZH: 'keywords_content',
        ParsedParaType.KEYWORDS_EN: 'keywords',
        ParsedParaType.KEYWORDS_CONTENT_EN: 'keywords_content',
        ParsedParaType.HEADING1: 'section',
        ParsedParaType.HEADING2: 'subsection',
        ParsedParaType.HEADING3: 'subsubsection',
        ParsedParaType.BODY: 'paragraph',
        ParsedParaType.FIGURES: 'figure',
        ParsedParaType.TABLES: 'table',
        ParsedParaType.REFERENCES: 'references',
        ParsedParaType.REFERENCES_CONTENT: 'reference_item',
        ParsedParaType.ACKNOWLEDGMENTS: 'acknowledgments',
        ParsedParaType.ACKNOWLEDGMENTS_CONTENT: 'acknowledgments_content',
        ParsedParaType.EQUATIONS: 'equation',
        ParsedParaType.OTHERS: 'paragraph',
    }

    def __init__(self, output_dir: str):
        """
        初始化 LaTeX 导出器

        Args:
            output_dir: 输出目录
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def export_to_latex(
        self,
        para_manager: ParagraphManager,
        original_filename: str,
        config_path: Optional[str] = None,
    ) -> LatexExportResult:
        """
        将文档导出为 LaTeX 格式

        Args:
            para_manager: 段落管理器
            original_filename: 原始文件名
            config_path: 格式配置文件路径（可选）

        Returns:
            LatexExportResult: 导出结果
        """
        export_id = f"latex_{uuid4().hex[:12]}"
        safe_name = self._safe_name(original_filename)
        latex_path = os.path.join(self.output_dir, f"{safe_name}_{export_id}.tex")

        try:
            # 加载配置（如果提供）
            config = self._load_config(config_path) if config_path else {}

            # 生成 LaTeX 内容
            latex_content = self._generate_latex_content(para_manager, config)

            # 写入文件
            with open(latex_path, 'w', encoding='utf-8') as f:
                f.write(latex_content)

            return LatexExportResult(
                export_id=export_id,
                latex_path=latex_path,
                success=True,
                paragraph_count=len(para_manager.paragraphs),
            )
        except Exception as e:
            return LatexExportResult(
                export_id=export_id,
                latex_path=latex_path,
                success=False,
                error_message=str(e),
            )

    def _generate_latex_content(self, para_manager: ParagraphManager, config: Dict) -> str:
        """
        生成 LaTeX 内容

        Args:
            para_manager: 段落管理器
            config: 配置字典

        Returns:
            str: LaTeX 内容
        """
        lines = []

        # 生成导言区
        lines.extend(self._generate_preamble(config))

        # 开始文档
        lines.append("\\begin{document}")
        lines.append("")

        # 处理标题、摘要等前置内容
        lines.extend(self._generate_front_matter(para_manager))

        # 处理主要内容
        lines.extend(self._generate_main_content(para_manager))

        # 处理参考文献
        lines.extend(self._generate_references(para_manager))

        # 结束文档
        lines.append("\\end{document}")

        return "\n".join(lines)

    def _generate_preamble(self, config: Dict) -> List[str]:
        """
        生成 LaTeX 导言区

        Args:
            config: 配置字典

        Returns:
            List[str]: 导言区内容
        """
        lines = [
            "% LaTeX document generated by Scriptor",
            "% https://github.com/yourusername/scriptor",
            "",
            "\\documentclass{article}",
            "",
            "% 中文支持",
            "\\usepackage[UTF8]{ctex}",
            "",
            "% 数学公式支持",
            "\\usepackage{amsmath}",
            "\\usepackage{amssymb}",
            "\\usepackage{mathtools}",
            "",
            "% 图形支持",
            "\\usepackage{graphicx}",
            "\\usepackage{float}",
            "",
            "% 表格支持",
            "\\usepackage{booktabs}",
            "\\usepackage{tabularx}",
            "",
            "% 超链接",
            "\\usepackage{hyperref}",
            "\\hypersetup{",
            "    colorlinks=true,",
            "    linkcolor=blue,",
            "    urlcolor=blue,",
            "    citecolor=blue,",
            "}",
            "",
            "% 页面设置",
        ]

        # 从配置中获取页面设置
        page_config = config.get('paper', {})
        lines.append(f"\\usepackage[{page_config.get('size', 'a4paper')}]{{geometry}}")

        margin_config = page_config.get('margins', {})
        geometry_options = []
        if 'top' in margin_config:
            geometry_options.append(f"top={margin_config['top']}")
        if 'bottom' in margin_config:
            geometry_options.append(f"bottom={margin_config['bottom']}")
        if 'left' in margin_config:
            geometry_options.append(f"left={margin_config['left']}")
        if 'right' in margin_config:
            geometry_options.append(f"right={margin_config['right']}")

        if geometry_options:
            lines.append(f"\\geometry{{{', '.join(geometry_options)}}}")

        lines.append("")
        lines.append("% 标题设置")
        lines.append("\\title{\\LaTeX Document}")
        lines.append("\\author{Author}")
        lines.append("\\date{\\today}")
        lines.append("")

        return lines

    def _generate_front_matter(self, para_manager: ParagraphManager) -> List[str]:
        """
        生成前置内容（标题、摘要等）

        Args:
            para_manager: 段落管理器

        Returns:
            List[str]: 前置内容
        """
        lines = []

        title_zh = None
        title_en = None
        abstract_zh = []
        abstract_en = []
        keywords_zh = []
        keywords_en = []

        for para in para_manager.paragraphs:
            if para.type == ParsedParaType.TITLE_ZH:
                title_zh = para.content
            elif para.type == ParsedParaType.TITLE_EN:
                title_en = para.content
            elif para.type in [ParsedParaType.ABSTRACT_ZH, ParsedParaType.ABSTRACT_CONTENT_ZH]:
                abstract_zh.append(para.content)
            elif para.type in [ParsedParaType.ABSTRACT_EN, ParsedParaType.ABSTRACT_CONTENT_EN]:
                abstract_en.append(para.content)
            elif para.type in [ParsedParaType.KEYWORDS_ZH, ParsedParaType.KEYWORDS_CONTENT_ZH]:
                keywords_zh.append(para.content)
            elif para.type in [ParsedParaType.KEYWORDS_EN, ParsedParaType.KEYWORDS_CONTENT_EN]:
                keywords_en.append(para.content)

        # 设置标题
        if title_zh or title_en:
            title = title_zh or title_en
            lines.append(f"\\title{{{self._escape_latex(title)}}}")
            lines.append("\\maketitle")
            lines.append("")

        # 中文摘要
        if abstract_zh:
            lines.append("\\begin{abstract}")
            for content in abstract_zh:
                if content.strip():
                    lines.append(f"    {self._escape_latex(content)}")
            lines.append("\\end{abstract}")
            lines.append("")

        # 英文摘要
        if abstract_en:
            lines.append("\\begin{abstract}")
            lines.append("    % English Abstract")
            for content in abstract_en:
                if content.strip():
                    lines.append(f"    {self._escape_latex(content)}")
            lines.append("\\end{abstract}")
            lines.append("")

        # 关键词
        if keywords_zh:
            keywords_text = " ".join(keywords_zh)
            lines.append(f"\\textbf{{关键词:}} {self._escape_latex(keywords_text)}")
            lines.append("")

        if keywords_en:
            keywords_text = " ".join(keywords_en)
            lines.append(f"\\textbf{{Keywords:}} {self._escape_latex(keywords_text)}")
            lines.append("")

        return lines

    def _generate_main_content(self, para_manager: ParagraphManager) -> List[str]:
        """
        生成主要内容

        Args:
            para_manager: 段落管理器

        Returns:
            List[str]: 主要内容
        """
        lines = []

        # 跳过已经处理过的前置内容类型
        skip_types = {
            ParsedParaType.TITLE_ZH,
            ParsedParaType.TITLE_EN,
            ParsedParaType.ABSTRACT_ZH,
            ParsedParaType.ABSTRACT_CONTENT_ZH,
            ParsedParaType.ABSTRACT_EN,
            ParsedParaType.ABSTRACT_CONTENT_EN,
            ParsedParaType.KEYWORDS_ZH,
            ParsedParaType.KEYWORDS_CONTENT_ZH,
            ParsedParaType.KEYWORDS_EN,
            ParsedParaType.KEYWORDS_CONTENT_EN,
            ParsedParaType.REFERENCES,
            ParsedParaType.REFERENCES_CONTENT,
        }

        for para in para_manager.paragraphs:
            if para.type in skip_types:
                continue

            latex_type = self.PARA_TYPE_TO_LATEX.get(para.type, 'paragraph')
            content = para.content.strip()

            if not content:
                continue

            if latex_type == 'section':
                lines.append(f"\\section{{{self._escape_latex(content)}}}")
                lines.append("")
            elif latex_type == 'subsection':
                lines.append(f"\\subsection{{{self._escape_latex(content)}}}")
                lines.append("")
            elif latex_type == 'subsubsection':
                lines.append(f"\\subsubsection{{{self._escape_latex(content)}}}")
                lines.append("")
            elif latex_type == 'equation':
                lines.append("\\begin{equation}")
                lines.append(f"    {self._process_equation(content)}")
                lines.append("\\end{equation}")
                lines.append("")
            elif latex_type == 'figure':
                lines.append("\\begin{figure}[H]")
                lines.append("    \\centering")
                lines.append(f"    \\caption{{{self._escape_latex(content)}}}")
                lines.append("    \\label{fig:placeholder}")
                lines.append("\\end{figure}")
                lines.append("")
            elif latex_type == 'table':
                lines.append("\\begin{table}[H]")
                lines.append("    \\centering")
                lines.append(f"    \\caption{{{self._escape_latex(content)}}}")
                lines.append("    \\label{tab:placeholder}")
                lines.append("    % Add table content here")
                lines.append("\\end{table}")
                lines.append("")
            else:
                # 普通段落
                lines.append(self._escape_latex(content))
                lines.append("")

        return lines

    def _generate_references(self, para_manager: ParagraphManager) -> List[str]:
        """
        生成参考文献

        Args:
            para_manager: 段落管理器

        Returns:
            List[str]: 参考文献内容
        """
        lines = []
        ref_items = []

        for para in para_manager.paragraphs:
            if para.type == ParsedParaType.REFERENCES_CONTENT:
                ref_items.append(para.content)

        if ref_items:
            lines.append("\\section*{参考文献}")
            lines.append("\\addcontentsline{toc}{section}{参考文献}")
            lines.append("")
            lines.append("\\begin{thebibliography}{99}")

            for i, ref in enumerate(ref_items, start=1):
                if ref.strip():
                    lines.append(f"    \\bibitem{{ref{i}}} {self._escape_latex(ref)}")

            lines.append("\\end{thebibliography}")
            lines.append("")

        return lines

    def _escape_latex(self, text: str) -> str:
        """
        转义 LaTeX 特殊字符

        Args:
            text: 原始文本

        Returns:
            str: 转义后的文本
        """
        if not text:
            return ""

        # LaTeX 特殊字符映射
        replacements = {
            '&': '\\&',
            '%': '\\%',
            '$': '\\$',
            '#': '\\#',
            '_': '\\_',
            '{': '\\{',
            '}': '\\}',
            '~': '\\textasciitilde{}',
            '^': '\\textasciicircum{}',
            '\\': '\\textbackslash{}',
        }

        result = text
        for char, replacement in replacements.items():
            result = result.replace(char, replacement)

        return result

    def _process_equation(self, text: str) -> str:
        """
        处理数学公式内容

        Args:
            text: 公式文本

        Returns:
            str: 处理后的公式
        """
        # 这里可以添加更复杂的公式处理逻辑
        # 暂时直接返回文本（假设已经是 LaTeX 格式）
        return text

    def _load_config(self, config_path: str) -> Dict:
        """
        加载配置文件

        Args:
            config_path: 配置文件路径

        Returns:
            Dict: 配置字典
        """
        if not config_path or not os.path.exists(config_path):
            return {}

        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception:
            return {}

    @staticmethod
    def _safe_name(filename: str) -> str:
        """
        生成安全的文件名

        Args:
            filename: 原始文件名

        Returns:
            str: 安全的文件名
        """
        name = os.path.splitext(os.path.basename(filename))[0]
        safe = "".join(ch for ch in name if ch.isalnum() or ch in "-_")
        return safe or "document"


def export_latex(
    para_manager: ParagraphManager,
    original_filename: str,
    output_dir: str,
    config_path: Optional[str] = None,
) -> LatexExportResult:
    """
    便捷函数：导出 LaTeX

    Args:
        para_manager: 段落管理器
        original_filename: 原始文件名
        output_dir: 输出目录
        config_path: 配置文件路径（可选）

    Returns:
        LatexExportResult: 导出结果
    """
    exporter = LatexExporter(output_dir)
    return exporter.export_to_latex(para_manager, original_filename, config_path)
